(function(){function formatInlineStyle(obj){let str='';for(let rule in obj){str+=`${rule}:${obj[rule]};`}
return str.trim();}
function initPdf(){return new Promise(function(resolve,reject){let jsPdfEl=document.createElement('script');jsPdfEl.type='text/javascript';jsPdfEl.src='https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.4.1/jspdf.min.js';jsPdfEl.onload=()=>resolve(new jsPDF());jsPdfEl.className='toCleanup';document.head.appendChild(jsPdfEl);});}
function getScoreImgUrl(scoreEl){let bkgImgUrl=scoreEl.style.backgroundImage;let pre=bkgImgUrl.indexOf("\(\"");let post=bkgImgUrl.indexOf("\"\)");let imgUrl=bkgImgUrl.substr(pre+2,post-5);return imgUrl;}
function drawToCanvas({el,url}){return new Promise(function(resolve,reject){let canvas=document.createElement("canvas");let context=canvas.getContext('2d');let base_image=new Image();base_image.onload=()=>{canvas.width=base_image.width;canvas.height=base_image.height;context.drawImage(base_image,0,0,base_image.width,base_image.height);resolve(canvas);};base_image.src=url;});}
function addCanvasToPdf({canvas,pdfDoc}){const blob=canvas.toDataURL();const imgType='PNG';const offset=0;const width=pdfDoc.internal.pageSize.getWidth();const height=pdfDoc.internal.pageSize.getHeight();pdfDoc.addImage(blob,imgType,offset,offset,width,height);}
function checkIsLastPage(){let rightButton=document.querySelectorAll('#rightbut2')[0];if(rightButton&&rightButton.style.visibility==='hidden'){return true;}
return rightButton.style.background.includes('rgb(192, 192, 192)');}
function setLoading(){let loadingDiv=document.createElement('div');loadingDiv.className=['loadingDiv','toCleanup'].join(' ');loadingDiv.textContent='generating your PDF, please wait...';loadingDiv.style=formatInlineStyle({'z-index':'999999','width':'100%','position':'fixed','top':'0','left':'0','display':'flex','flex-direction':'column','justify-content':'center','align-items':'center','padding':'3em 0','border':'1px solid black','background-color':'honeydew','text-align':'center','font-size':'1.4em'});document.body.appendChild(loadingDiv);}
function completeLoading({formattedTitle,promptFileDownload}){const loadingDiv=document.querySelector('.loadingDiv');const closeAndCleanup=()=>{const toCleanup=document.querySelectorAll('.toCleanup');for(let el of[].slice.call(toCleanup)){el.parentNode.removeChild(el);}};const closeButton=document.createElement('button');closeButton.onclick=closeAndCleanup;closeButton.ariaLabel='close';closeButton.style=formatInlineStyle({'position':'absolute','top':'1em','right':'1em','padding':'.2em','background-color':'mintcream','cursor':'pointer'});const closeButtonInner=document.createElement('span');closeButtonInner.textContent='x';closeButtonInner.style=formatInlineStyle({'display':'inline-flex','justify-content':'center','align-items':'center','position':'relative','top':'-0.1em','height':'1.4em','width':'1.4em','font-size':'2em','color':'silver'});closeButton.appendChild(closeButtonInner);const styles={mainLine:{'padding':'.5em 0','font-size':'1.2em'},title:{'padding':'.2em','text-decoration':'underline','font-weight':'bold'}};const content=document.createElement('div');content.innerHTML=`thanks for waiting!<div style="${formatInlineStyle(styles.mainLine)}">your download of<span style="${formatInlineStyle(styles.title)}">${formattedTitle}</span>is beginning now.</div>to manually download the file, click here:`;const downloadLink=document.createElement('a');downloadLink.onclick=promptFileDownload;downloadLink.textContent='download PDF';downloadLink.style='cursor: pointer';loadingDiv.innerHTML='';loadingDiv.appendChild(closeButton);loadingDiv.appendChild(content);loadingDiv.appendChild(downloadLink);setTimeout(closeAndCleanup,500000);}
async function main(){setLoading();const pdfDoc=await initPdf();async function addCurrentScoreImgToPdf(){const scoreEl=document.querySelectorAll('#score')[0];let canvas=await drawToCanvas({el:scoreEl,url:getScoreImgUrl(scoreEl),});addCanvasToPdf({canvas,pdfDoc});}
let isLastPage=checkIsLastPage();while(!isLastPage){await addCurrentScoreImgToPdf();changepage('r');pdfDoc.addPage();isLastPage=checkIsLastPage();}
await addCurrentScoreImgToPdf();const rawTitle=document.querySelector('h1').textContent;const formattedTitle=rawTitle.substr(0,rawTitle.indexOf('sheet music')).trim();const promptFileDownload=()=>pdfDoc.output('save',`${formattedTitle}.pdf`);completeLoading({promptFileDownload,formattedTitle});promptFileDownload();}
main();})();